Ejercicios pandas 2017 resueltos, 2018 comienzo
CrossNox/ejs_spark pull request #15
Opened 2018-10-09 01:54 UTC by FdelMazo

2018-10-09 02:41 UTC, FdelMazo commented
Closes #6

2018-10-22 11:24 UTC, CrossNox requested changes
En general, muy buen aporte! 
Lo único que quiero resaltar es de flujo de trabajo: los archivos de ejemplo (que supongo son los que te trababan) no veo por que no podriamos pushear de una o laburar en PRs separados (porque master está protegida), y me gustaría que los PRs sean más atómicos, para que sean más rapidos de ver, comentar y agregar valor al repo

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C1_1_ebooks.ipynb
> +    "1. Filtrar los libros con un mínimo de ratings, para evitar caer en #LaEcuacionMasPeligrosa. Lo que se intenta evitar es que un libro desconocido que solo una persona le haya puesto 5 estrellas
No hace falta, el campo era avg_rating, no ratings

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_1_playlists.ipynb
> +    "* Hacemos un value counts de los cantantes\n",
Que sean pasos mas genericos

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_1_playlists.ipynb
> +    "valores = agrupado['singer'].value_counts()\n",
un metodo mucho mas sencillo de resolver el ejercicio sin meterse en quilombos de multi-indices es con esta linea: `df_playlist.merge(df_canciones, how='left').groupby('playlist')['singer'].agg(lambda x:x.mode())`, que cumple los pasos que pusiste al principio y es mucho mas pythonico

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "# Alternativa (muy Sparkesca):\n",
Yo sacaria esto para no confundir al lector. Ademas que son ejercicios de spark, para eso estan las otras soluciones

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "# Alternativa (muy Sparkesca):\n",
Y porque son ejercicios de spark, para eso esta la otra resolucion

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "nacimientos_por_hospital = nacimientos_por_hospital.to_frame()\n",
No hace falta, podes hacer `join` de un DataFrame con una Series si la Series tiene el nombre seteado

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "porcentaje_2016 = octubre_2016[octubre_2016['tipo_parto']==2].shape[0] / octubre_2016.shape[0]\n",
```suggestion
    "porcentaje_2016 = (octubre_2016.tipo_parto == 2).mean()\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "if porcentaje_2017>porcentaje_2016: print(True)\n",
```suggestion
    "if porcentaje_2017>porcentaje_2016: print("Se incrementó el % de cesáreas")\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "else: print(False)"
```suggestion
    "else: print("No incrementó el % de cesáreas")"
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "if porcentaje_2017>porcentaje_2016: print(True)\n",
En cuanto a estilo, me parece más prolijo `print(porcentaje_2017 > porcentaje_2016)` en todo caso

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "nacimientos_por_hospital = nacimientos_por_hospital.to_frame()\n",
El código relevante termina siendo algo del estilo
`no = nacimientos_octubre.groupby('id_hospital').size().rename("nacimientos_octubre")
df_1 = df_historico.join(no,on='id_hospital')
df_1[df_1.nacimientos_octubre > df_1.promedio_nacimientos_mensual][["id_hospital","dirección"]]`

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "- Tasa de resolución de casos de la fuerza policial por categoría de caso (considerando aquellos casos en los que no participó Batman). \n",
Me queda la duda de si es *solo* los que no participó batman

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df.groupby(['categoria','estado_caso']).agg('size').to_frame()\n",
Podemos evitar todo el bardo de `unstack`, `to_frame`, `droplevel` por una solucion mas idiomatica como `df.groupby(['categoria'])['estado_caso'].agg(lambda x: (x == 2).mean()).rename('tasa de resolución')` ?

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df_gcpd.merge(df_con_batman, how='inner',left_on='id_caso',right_on='id_caso')\n",
```suggestion
    "df = df_gcpd.merge(df_con_batman, how='inner',on='id_caso')\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df.groupby(['categoria','estado_caso']).agg('size').to_frame().unstack(fill_value=0)\n",
Same as above, `df.groupby(['categoria'])['estado_caso'].agg(lambda x: (x == 2).mean()).rename('tasa de resolución')`

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> + ],
Faltaria el tercer punto, se puede resolver con algo asi:
`df_con_batman = df_gordon.loc[df_gordon['respuesta']==1]
df = df_gcpd.merge(df_con_batman, how='inner',on='id_caso')
df[df.fecha.str.startswith("2017")].fecha.apply(lambda x: x.split('-')[1]).mode()`

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "ttdf_trim_actual = df_gcpd.loc[(df_gcpd['fecha'].dt.year==2017) & (df_gcpd['fecha'].dt.month.isin(trimestre_actual))]\n",
Correccion de typo

```suggestion
    "df_trim_actual = df_gcpd.loc[(df_gcpd['fecha'].dt.year==2017) & (df_gcpd['fecha'].dt.month.isin(trimestre_actual))]\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "df_trim_anterior.groupby('categoria')."
No pusheemos resoluciones incompletas pls, no puede mergearse asi

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "df_trim_anterior.groupby('categoria')."
Resolución:
`
df_tasa_por_trimestre = df_gcpd.pivot_table(columns='trimestre',index='categoria',aggfunc=lambda x: (x==2).mean(),values='estado_caso').fillna(0)
df_tasa_por_trimestre[df_tasa_por_trimestre[3] > df_tasa_por_trimestre[2]].index.values.tolist()
`

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "df_trim_anterior.groupby('categoria')."
No hace falta separar en dos dataframes, se puede trabajar todo junto

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +   "cell_type": "code",
Para la segunda parte, una propuesta:
`DELITOS_CONTRA_LA_PROPIEDAD = set(['Incendio', 'Robo', 'Hurto', 'Robo de Vehículo'])
df = df_gcpd.merge(df_gordon,how='left',on='id_caso')
df = df[df.categoria.isin(DELITOS_CONTRA_LA_PROPIEDAD)]
df.groupby('categoria')['estado_caso'].apply(lambda x: (x==2).mean())`

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "df_trim_anterior.groupby('categoria')."
Tratemos de no pushear resoluciones incompletas, esto no se puede mergear a master asi

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +   "cell_type": "code",
Propuesta para la segunda parte:
```DELITOS_CONTRA_LA_PROPIEDAD = set(['Incendio', 'Robo', 'Hurto', 'Robo de Vehículo'])
df = df_gcpd.merge(df_gordon,how='left',on='id_caso')
df = df[df.categoria.isin(DELITOS_CONTRA_LA_PROPIEDAD)]
df.groupby('categoria')['estado_caso'].apply(lambda x: (x==2).mean())```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_2_GCPD.ipynb
> +    "df_trim_anterior = df_gcpd.loc[(df_gcpd['fecha'].dt.year==2017) & (df_gcpd['fecha'].dt.month.isin(trimestre_anterior))]\n",
No hay necesidad de separar el dataframe:
```df_gcpd['fecha'] = pd.to_datetime(df_gcpd['fecha'],format='%Y-%m-%d')
df_gcpd['trimestre'] = df_gcpd.fecha.dt.month % 4
df_gcpd = df_gcpd[df_gcpd.trimestre.isin([3,2])]
df_tasa_por_trimestre = df_gcpd.pivot_table(columns='trimestre',index='categoria',aggfunc=lambda x: (x==2).mean(),values='estado_caso').fillna(0)
df_tasa_por_trimestre[df_tasa_por_trimestre[3] > df_tasa_por_trimestre[2]].index.values.tolist()```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "# Set-up y vista rápida de las dos bases de datos truchas\n",
```suggestion
    "# Set-up y vista rápida de los dos datasets sintéticos\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df_gcpd.merge(df_sin_batman, how='left', left_on='id_caso',right_on='id_caso')\n",
```suggestion
    "df = df_gcpd.merge(df_sin_batman, how='left', on='id_caso')\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df.groupby(['categoria','estado_caso']).agg('size').to_frame()\n",
Para evitar todo el bardo del `to_frame`, `unstack`, `droplevel`, etc, propongo algo mas idiomatico:
```df.groupby(['categoria'])['estado_caso'].apply(lambda x: (x==2).mean()).rename('tasa de resolucion')```
despues del `fillna` previo, no hace falta filtrar las columnas

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> +    "df = df.groupby(['categoria','estado_caso']).agg('size').to_frame().unstack(fill_value=0)\n",
Lo mismo que antes

2018-10-22 11:24 UTC, CrossNox commented on pandas/2018C1_1_GCPD.ipynb
> + "metadata": {
Propuesta para el último punto:
```df_con_batman = df_gordon.loc[df_gordon['respuesta']==1]
df = df_gcpd.merge(df_con_batman, how='inner',on='id_caso')
df[df.fecha.str.startswith("2017")].fecha.apply(lambda x: x.split('-')[1]).mode()```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "nacimientos_por_hospital.rename(columns={0:'count_nacimientos'},inplace=True)\n",
No hace falta, podes hacer un join de un DataFrame con una Series si la Series tiene nombre. Te evitás el to_frame y cosas así:
```no = nacimientos_octubre.groupby('id_hospital').size().rename("nacimientos_octubre")
df_1 = df_historico.join(no,on='id_hospital')
df_1[df_1.nacimientos_octubre > df_1.promedio_nacimientos_mensual][["id_hospital","dirección"]]```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "porcentaje_2016 = octubre_2016[octubre_2016['tipo_parto']==2].shape[0] / octubre_2016.shape[0]\n",
```suggestion
    "porcentaje_2016 = (octubre_2016.tipo_parto == 2).mean()\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "if porcentaje_2017>porcentaje_2016: print(True)\n",
```suggestion
    "print(porcentaje_2017 > porcentaje_2016)\n",
```

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "if porcentaje_2017>porcentaje_2016: print(True)\n",
En todo caso pondría algo del estilo "se/no aumento el % etc, etc"

2018-10-22 11:24 UTC, CrossNox commented on pandas/2017C2_2_nacimientos.ipynb
> +    "porcentaje_2017 = octubre_2017[octubre_2017['tipo_parto']==2].shape[0] / octubre_2017.shape[0]\n",
Algo mucho mas idiomático sería:
```
octubre = df_nacimientos[df_nacimientos['mes_nacimiento'] == 10].groupby('anio_nacimiento')['tipo_parto'].apply(lambda x: (x==2).mean())
octubre[2017] > octubre[2016]
```

2018-10-24 15:14 UTC, FdelMazo commented on pandas/2017C1_1_ebooks.ipynb
> +    "1. Filtrar los libros con un mínimo de ratings, para evitar caer en #LaEcuacionMasPeligrosa. Lo que se intenta evitar es que un libro desconocido que solo una persona le haya puesto 5 estrellas
No entendí, justamente hay que agarrar por promedio, pero no los que tengan pocos registros. No?

2018-10-24 15:23 UTC, FdelMazo commented on pandas/2018C1_1_GCPD.ipynb
> +    "- Tasa de resolución de casos de la fuerza policial por categoría de caso (considerando aquellos casos en los que no participó Batman). \n",
Si, lo aclaramos en clase.

2018-10-24 15:51 UTC, CrossNox commented on pandas/2017C1_1_ebooks.ipynb
> +    "1. Filtrar los libros con un mínimo de ratings, para evitar caer en #LaEcuacionMasPeligrosa. Lo que se intenta evitar es que un libro desconocido que solo una persona le haya puesto 5 estrellas
No lei que era del primer df, pensé que era del segundo. Viendo eso, voy a revisar de vuelta la solución 👍 
A ojo, sin poder levantar los notebooks ahora, otra opción ademas de filtrar sería utilizar un score que tome en cuenta la cantidad de reviews. Algo como el score de Wilson pero para intervalos de confianza simultáneos para proporciones multinomiales si el rating es 5-star based, por ejemplo. Si se filtra habría que calcular la cantidad de reviews necesarias para conocer la verdadera media con ponele un .95 de confianza y cortar por ese treshold.

2018-10-24 22:18 UTC, FdelMazo commented on pandas/2017C1_1_ebooks.ipynb
> +    "1. Filtrar los libros con un mínimo de ratings, para evitar caer en #LaEcuacionMasPeligrosa. Lo que se intenta evitar es que un libro desconocido que solo una persona le haya puesto 5 estrellas
Siento que  estan siendo soluciones poco parcialescas! Quiero que evitemos oneliners y cosas no muy vistas en clase.

2018-10-25 14:40 UTC, CrossNox approved these changes

2018-10-25 14:41 UTC, merged