Resolución del ejercicio de PySpark, 2018C1_1
CrossNox/ejs_spark pull request #18
Opened 2018-10-10 05:40 UTC by ndvazquez

En el paso 2  hago un map que _podría_ considerarse innecesario, pero el reduceByKey va a hacer eso mismo de todas formas así que no creo que tenga impacto sobre la performance (de hecho si hay una clave con una única ocurrencia, podría llegar a devolver una tupla `(id_tienda, (total_ventas, estado))`).

2018-10-17 15:00 UTC, FdelMazo approved these changes

2018-10-17 15:00 UTC, FdelMazo commented
Closes #11

2018-10-17 15:02 UTC, FdelMazo commented
Closes #9

2018-10-20 22:16 UTC, CrossNox requested changes

2018-10-20 22:16 UTC, CrossNox commented on spark/2018C1_1_Nintendo.ipynb
> +    "Notar que en algún punto de la resolución, va a ser necesario hacer un **join** de los RDDs, por lo cual debemos hacer el filtrado de los datos _antes_ de unirlos, para de esta forma hacer menos
Podes hacer el filter antes, recolectar los ids, hacer broadcast de esa lista y tambien funcionaria

2018-10-20 22:16 UTC, CrossNox commented on spark/2018C1_1_Nintendo.ipynb
> +    "#  Header de rdd_ventas: [id_videojuego, id_tienda, mes, anio, total_ventas_mensuales].\n",
```suggestion
    "#  Header de rdd_ventas: [id_videojuego, id_tienda, mes, año, total_ventas_mensuales].\n",
```

2018-10-20 22:16 UTC, CrossNox commented on spark/2018C1_1_Nintendo.ipynb
> +    "#  Índice de anio: 3.\n",
```suggestion
    "#  Índice de año: 3.\n",
```

2018-10-20 22:16 UTC, CrossNox commented on spark/2018C1_1_Nintendo.ipynb
> +    "#  Filtramos rdd_ventas para quedarnos con aquellos registros cuyo anio sea 2017, luego nos quedamos con tuplas\n",
```suggestion
    "#  Filtramos rdd_ventas para quedarnos con aquellos registros cuyo año sea 2017, luego nos quedamos con tuplas\n",
```

2018-10-20 22:16 UTC, CrossNox commented on spark/2018C1_1_Nintendo.ipynb
> +    "rdd_union.reduceByKey(lambda a,b: a+b).reduce(lambda a,b: a if a < b else b)"
Pls se podra poner de un modo mas humano la salida?

2018-12-27 05:58 UTC, CrossNox approved these changes

2018-12-27 05:58 UTC, merged